todo_app/urls.py
from django.urls import path
from . import views

app_name = 'todo_app'
urlpatterns = [

    path('',views.hello, name='hello'),
    path('delete/<int:taskid>',views.delete, name='delete'),
    path('update/<int:id>',views.update, name='update'),
    path('cvbhome/',views.Tasklistview.as_view(),name='cvbhome'),
    path('cvbdetail/<int:pk>',views.Taskdetailview.as_view(),name='cvbdetail'),
    path('cvbupdate/<int:pk>',views.TaskUpdateView.as_view(),name='cvbUpdate'),
]

todo_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo_app.urls')),

]

todo_app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.TextField(max_length=200)
    work=models.TextField()
    date=models.DateField()
    def __str__(self):
        return self.name

todo_app/forms.py
from .models import Task
from django import forms

class todoform(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','work','date']

todo_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from .models import Task
from .forms import todoform
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

class Tasklistview(ListView):
    model = Task
    template_name = 'index.html'
    context_object_name = 'task1'

class Taskdetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task1'

class TaskUpdateView(UpdateView):
    model = Task
    template_name = 'edit.html'
    context_object_name = 'task1'
    fields = ('name', 'work', 'date')

    def get_success_url(self):
        return reverse_lazy('cvbdetail', kwargs={'pk':self.object.id})

# Create your views here.
def hello(request):
    task1=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('name',)
        work=request.POST.get('work',)
        date=request.POST.get('date',)
        task=Task(name=name,work=work,date=date)
        task.save()

    return render(request,'index.html',{'task1':task1})
def delete(request,taskid):
    tast2=Task.objects.get(id=taskid)
    if request.method=='POST':
        tast2.delete()
        return redirect('/')
    return render(request,'delete.html')
def update(request,id):
    task=Task.objects.get(id=id)
    f=todoform(request.POST or None, instance=task)
    if f.is_valid():
        f.save()
        return redirect('/')

    return render(request,'edit.html',{'f':f,'task':task})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<body >
<head \>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<div class="container-fluid">
   <div class="row">
       <div class="col-md-12">
           <div class="banner" style="background-color:grey;">
               <div class="banner-text" style="text-align:center;">
                   <h1><b>TODO</b></h1>
               </div>
           </div>
       </div>
   </div>
</div>

{% block content %}
{% endblock %}
</body>

</html>

templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <h5>do you completed this</h5>
    <input type="submit">
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}
<body>
<div class="col-md-6">
            <h3> <i><b>task to be completed</b></i></h3>
            <br>
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{task1.name}}</h5>
                    <p><b>{{task1.work}}</b></p>
                    <p><b>{{task1.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todo_app:delete' task1.id %}">done</a>
                    <a class="btn btn-warning" href="{% url 'todo_app:update' task1.id %}">Update</a>

                </div>
            </div>
        </div>

</body>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block content %}

        <div class="card">
            <div class="card-header">
                <div class="card-title">update</div>
                <div class="card-body">

                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{f.as_p}}
                            <input type="submit">
                        </form>


                </div>
            </div>
        </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
        <form method="POST" class="mb-3 shadow">
            {% csrf_token %}
            <div class="form-group">
                <br>
                <input type="text" class="form-control" placeholder="name" name="name"><br>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="work" name="work"><br>
            </div>
            <div class="form-group">
                <input type="date" class="form-control" name="date"><br>
            </div>

    <input type="submit" class="btn btn-success"><br>





    </div>
        <div class="col-md-6">
            <h3> <i><b>task to be completed<b/></i></h3>
            {% for i in task1 %}
            <br>
            <div class="shadow card">
                <div class="card-body">
                    <h5 class="card-title">{{i.name}}</h5>
                    <p><b>{{i.work}}</b></p>
                    <p><b>{{i.date}}</b></p>
                    <a class="btn btn-danger" href="{% url 'todo_app:delete' i.id %}">done</a>
                    <a class="btn btn-warning" href="{% url 'todo_app:update' i.id %}">Update</a>

                </div>
            </div>
           {% endfor %}
        </div>
    </div>
</div>


{% endblock %}